"""Golden metrics: results/metrics.json is asserted byte-for-byte, ZERO tolerance.

DoD criterion 1 ("a fresh clone regenerates every number bit-for-bit") as a test:
the metrics are regenerated in memory from the hash-pinned data and compared against
the committed file on RAW BYTES -- not read_text(), whose universal-newline
translation would let a CRLF-rewritten file pass -- with no numeric tolerance of any
kind. A single float that moves anywhere (an engine change, a data change, a config
change) breaks the build; the fix is never to loosen this test, it is to either
revert the regression or knowingly regenerate and commit the diff.

Platform scope: bit-for-bit holds on the prescribed environment (Linux x86-64 /
glibc -- the CI image and WSL). Another libm may round ``**`` (cagr's only
transcendental call) 1 ulp differently and fail this test loudly; that is the test
doing its job on an unsupported platform, not a tolerance to add.
"""

from __future__ import annotations

import json
import math
from typing import Any

import pytest

from engine.metrics import calendar_bars_per_year
from scripts.generate_results import (
    METRICS_PATH,
    PREREG_ALARM_SHARPE,
    PREREG_SHARPE_HI,
    PREREG_SHARPE_LO,
    PREREG_TSTAT_MAX,
    README_PATH,
    RESULTS_TIMEFRAME,
    Computed,
    compute_all,
    render_metrics_json,
)

REGEN_HINT = "run `python -m scripts.generate_results` and commit the diff"


@pytest.fixture(scope="module")
def computed() -> Computed:
    """One in-memory computation shared by the tests of this module."""
    return compute_all()


@pytest.fixture(scope="module")
def regenerated(computed: Computed) -> str:
    return render_metrics_json(computed)


def test_golden_metrics_file_is_committed() -> None:
    assert METRICS_PATH.exists(), f"results/metrics.json is missing -- {REGEN_HINT}"


def test_golden_metrics_match_committed_file_exactly(regenerated: str) -> None:
    """THE golden check: regenerated bytes == committed bytes. No tolerance."""
    committed = METRICS_PATH.read_bytes()
    assert regenerated.encode("utf-8") == committed, (
        "results/metrics.json is out of sync with the code/data -- a number moved, "
        f"byte-for-byte. If the change is intended, {REGEN_HINT}; "
        "if it is not, this is a regression: stop and find out why."
    )


def test_golden_metrics_is_strict_json_with_explicit_nonfinite() -> None:
    """The committed file must parse as STRICT JSON: no bare NaN/Infinity tokens.

    Non-finite values are stored as the explicit strings "NaN"/"Infinity"/"-Infinity"
    (see ``scripts.generate_results._json_ready``), so a strict parse must succeed.
    """

    def _reject(token: str) -> None:
        pytest.fail(f"bare {token} token in metrics.json -- strict JSON forbids it")

    payload = json.loads(METRICS_PATH.read_bytes().decode("utf-8"), parse_constant=_reject)
    assert set(payload) == {"config", "data", "full_sample", "walk_forward"}


def test_golden_metrics_pins_all_data_hashes() -> None:
    """Both timeframes of both symbols must be pinned by SHA-256 in the golden file."""
    payload: dict[str, Any] = json.loads(METRICS_PATH.read_bytes().decode("utf-8"))
    for symbol in ("BTC/USDT", "ETH/USDT"):
        for timeframe in ("1d", "1h"):
            sha = payload["data"][symbol][timeframe]["sha256"]
            assert isinstance(sha, str) and len(sha) == 64


def test_prereg_constants_match_the_dated_readme_prose() -> None:
    """The dated pre-registration prose is frozen; the code constants must match it.

    The bounds are hand-written in the README on purpose (a pre-registration must be
    frozen text, not regenerated output), which leaves them duplicated in the
    ``PREREG_*`` constants that render the generated check. This test pins the two
    together: editing either side alone breaks the build, so the promise "not edited
    since" stays machine-checked.
    """
    readme = README_PATH.read_bytes().decode("utf-8").replace("−", "-")
    assert f"[{PREREG_SHARPE_LO:+.1f}, {PREREG_SHARPE_HI:+.1f}]" in readme
    assert f"|t-stat| < {PREREG_TSTAT_MAX:.0f}" in readme
    assert f"OOS Sharpe > {PREREG_ALARM_SHARPE:.1f}" in readme


def test_carried_boundaries_are_exactly_one_per_symbol_and_config(computed: Computed) -> None:
    """A3 pin: on the published 1d runs, exactly ONE fold boundary carries a
    position (fold 4 -> fold 5, 2024-11-17 -> 2024-11-18) for each symbol, in BOTH
    configurations. This count is what moved the OOS figures when splicing was
    introduced; if it ever changes, the published numbers move with it -- so it is
    asserted here, from the engine's own counter."""
    for symbol, by_config in computed.walkforward.items():
        for config_name, result in by_config.items():
            assert result.n_carried_boundaries == 1, (
                f"{symbol} {config_name}: expected exactly 1 carried boundary, "
                f"got {result.n_carried_boundaries}"
            )


def test_prereg_correction_note_numbers_match_the_computed_run(computed: Computed) -> None:
    """The dated 2026-07-26 correction note quotes data-derived numbers (range width
    in SE, per-symbol deviations in SE, before and after the splice correction);
    every one of them is recomputed here from the shared in-memory run and must
    appear in the README verbatim -- hand-written numbers stay machine-checked."""
    readme = README_PATH.read_bytes().decode("utf-8").replace("−", "-")

    (oos_bars,) = {
        len(result.oos.returns)
        for by_config in computed.walkforward.values()
        for result in by_config.values()
    }
    years = oos_bars / calendar_bars_per_year(RESULTS_TIMEFRAME)
    theoretical_se = 1.0 / math.sqrt(years)  # the note's "1/sqrt(0.600 years) = 1.29"
    assert f"1/√{years:.3f} years = {theoretical_se:.2f}" in readme
    width = (PREREG_SHARPE_HI - PREREG_SHARPE_LO) / theoretical_se
    assert f"**{width:.2f} SE** wide" in readme

    deviations: dict[str, tuple[float, float]] = {}
    for symbol, by_config in computed.walkforward.items():
        m = by_config["anchored"].metrics
        splice = computed.splice[symbol]["anchored"]
        spliced_dev = (PREREG_SHARPE_LO - m["sharpe"]) / m["sharpe_se"]
        standalone_dev = (PREREG_SHARPE_LO - splice["standalone_sharpe"]) / splice[
            "standalone_sharpe_se"
        ]
        deviations[symbol.split("/")[0]] = (spliced_dev, standalone_dev)
    btc, eth = deviations["BTC"], deviations["ETH"]
    assert f"**{btc[0]:.2f} SE (BTC)** and **{eth[0]:.2f} SE (ETH)**" in readme
    assert f"({btc[1]:.2f} SE and {eth[1]:.2f} SE under the flat-restart" in readme
