"""Golden metrics: results/metrics.json is asserted byte-for-byte, ZERO tolerance.

DoD criterion 1 ("a fresh clone regenerates every number bit-for-bit") as a test:
the metrics are regenerated in memory from the hash-pinned data and compared against
the committed file on RAW BYTES -- not read_text(), whose universal-newline
translation would let a CRLF-rewritten file pass -- with no numeric tolerance of any
kind. A single float that moves anywhere (an engine change, a data change, a config
change) breaks the build; the fix is never to loosen this test, it is to either
revert the regression or knowingly regenerate and commit the diff.

Platform scope: bit-for-bit holds on the prescribed environment (Linux x86-64 /
glibc -- the CI image and WSL). Another libm may round ``**`` (cagr's only
transcendental call) 1 ulp differently and fail this test loudly; that is the test
doing its job on an unsupported platform, not a tolerance to add.
"""

from __future__ import annotations

import json
from typing import Any

import pytest

from scripts.generate_results import (
    METRICS_PATH,
    PREREG_ALARM_SHARPE,
    PREREG_SHARPE_HI,
    PREREG_SHARPE_LO,
    PREREG_TSTAT_MAX,
    README_PATH,
    compute_all,
    render_metrics_json,
)

REGEN_HINT = "run `python -m scripts.generate_results` and commit the diff"


@pytest.fixture(scope="module")
def regenerated() -> str:
    """One in-memory regeneration shared by the tests of this module."""
    return render_metrics_json(compute_all())


def test_golden_metrics_file_is_committed() -> None:
    assert METRICS_PATH.exists(), f"results/metrics.json is missing -- {REGEN_HINT}"


def test_golden_metrics_match_committed_file_exactly(regenerated: str) -> None:
    """THE golden check: regenerated bytes == committed bytes. No tolerance."""
    committed = METRICS_PATH.read_bytes()
    assert regenerated.encode("utf-8") == committed, (
        "results/metrics.json is out of sync with the code/data -- a number moved, "
        f"byte-for-byte. If the change is intended, {REGEN_HINT}; "
        "if it is not, this is a regression: stop and find out why."
    )


def test_golden_metrics_is_strict_json_with_explicit_nonfinite() -> None:
    """The committed file must parse as STRICT JSON: no bare NaN/Infinity tokens.

    Non-finite values are stored as the explicit strings "NaN"/"Infinity"/"-Infinity"
    (see ``scripts.generate_results._json_ready``), so a strict parse must succeed.
    """

    def _reject(token: str) -> None:
        pytest.fail(f"bare {token} token in metrics.json -- strict JSON forbids it")

    payload = json.loads(METRICS_PATH.read_bytes().decode("utf-8"), parse_constant=_reject)
    assert set(payload) == {"config", "data", "full_sample", "walk_forward"}


def test_golden_metrics_pins_all_data_hashes() -> None:
    """Both timeframes of both symbols must be pinned by SHA-256 in the golden file."""
    payload: dict[str, Any] = json.loads(METRICS_PATH.read_bytes().decode("utf-8"))
    for symbol in ("BTC/USDT", "ETH/USDT"):
        for timeframe in ("1d", "1h"):
            sha = payload["data"][symbol][timeframe]["sha256"]
            assert isinstance(sha, str) and len(sha) == 64


def test_prereg_constants_match_the_dated_readme_prose() -> None:
    """The dated pre-registration prose is frozen; the code constants must match it.

    The bounds are hand-written in the README on purpose (a pre-registration must be
    frozen text, not regenerated output), which leaves them duplicated in the
    ``PREREG_*`` constants that render the generated check. This test pins the two
    together: editing either side alone breaks the build, so the promise "not edited
    since" stays machine-checked.
    """
    readme = README_PATH.read_bytes().decode("utf-8").replace("−", "-")
    assert f"[{PREREG_SHARPE_LO:+.1f}, {PREREG_SHARPE_HI:+.1f}]" in readme
    assert f"|t-stat| < {PREREG_TSTAT_MAX:.0f}" in readme
    assert f"OOS Sharpe > {PREREG_ALARM_SHARPE:.1f}" in readme
