"""Golden metrics: results/metrics.json is asserted byte-for-byte, ZERO tolerance.

DoD criterion 1 ("a fresh clone regenerates every number bit-for-bit") as a test:
the metrics are regenerated in memory from the hash-pinned data and compared against
the committed file on RAW BYTES -- not read_text(), whose universal-newline
translation would let a CRLF-rewritten file pass -- with no numeric tolerance of any
kind. A single float that moves anywhere (an engine change, a data change, a config
change) breaks the build; the fix is never to loosen this test, it is to either
revert the regression or knowingly regenerate and commit the diff.

Platform scope: bit-for-bit holds on the prescribed environment (Linux x86-64 /
glibc -- the CI image and WSL). Another libm may round ``**`` (cagr's only
transcendental call) 1 ulp differently and fail this test loudly; that is the test
doing its job on an unsupported platform, not a tolerance to add.
"""

from __future__ import annotations

import json
import math
from typing import Any

import pytest

from engine.evaluate import WalkForwardResult, walk_forward_evaluate
from engine.metrics import calendar_bars_per_year
from engine.splits import walk_forward_splits
from scripts.generate_results import (
    CONFIG,
    METRICS_PATH,
    PREREG_ALARM_SHARPE,
    PREREG_SHARPE_HI,
    PREREG_SHARPE_LO,
    PREREG_TSTAT_MAX,
    README_PATH,
    RESULTS_TIMEFRAME,
    WF_EMBARGO,
    WF_GRID,
    WF_N_FOLDS,
    WF_PURGE,
    WF_SELECTION_METRIC,
    WF_TEST_SIZE,
    Computed,
    _ma_factory,
    _splice_stats,
    compute_all,
    render_metrics_json,
)

REGEN_HINT = "run `python -m scripts.generate_results` and commit the diff"
ARCHIVE_PATH = METRICS_PATH.parent / "archive" / "metrics-2022-2024.json"


@pytest.fixture(scope="module")
def computed() -> Computed:
    """One in-memory computation shared by the tests of this module."""
    return compute_all()


@pytest.fixture(scope="module")
def regenerated(computed: Computed) -> str:
    return render_metrics_json(computed)


@pytest.fixture(scope="module")
def slice_2022_2024(computed: Computed) -> dict[str, dict[str, WalkForwardResult]]:
    """The 2022-01-01..2024-12-31 slice of the CURRENT data, run through the
    engine with the exact published protocol -- the object of the B4
    pre-registration's prediction (d)."""
    out: dict[str, dict[str, WalkForwardResult]] = {}
    for symbol, prices in computed.prices.items():
        prices_slice = prices.loc["2022-01-01":"2024-12-31"]
        assert len(prices_slice) == 1096  # the old sample is an exact subset
        out[symbol] = {}
        for config_name, anchored in (("anchored", True), ("rolling", False)):
            splits = walk_forward_splits(
                len(prices_slice),
                WF_N_FOLDS,
                WF_TEST_SIZE,
                WF_PURGE,
                WF_EMBARGO,
                anchored=anchored,
            )
            out[symbol][config_name] = walk_forward_evaluate(
                prices_slice,
                _ma_factory,
                WF_GRID,
                splits,
                CONFIG,
                WF_SELECTION_METRIC,
                RESULTS_TIMEFRAME,
            )
    return out


def test_golden_metrics_file_is_committed() -> None:
    assert METRICS_PATH.exists(), f"results/metrics.json is missing -- {REGEN_HINT}"


def test_golden_metrics_match_committed_file_exactly(regenerated: str) -> None:
    """THE golden check: regenerated bytes == committed bytes. No tolerance."""
    committed = METRICS_PATH.read_bytes()
    assert regenerated.encode("utf-8") == committed, (
        "results/metrics.json is out of sync with the code/data -- a number moved, "
        f"byte-for-byte. If the change is intended, {REGEN_HINT}; "
        "if it is not, this is a regression: stop and find out why."
    )


def test_golden_metrics_is_strict_json_with_null_for_undefined() -> None:
    """The committed file must parse as STRICT JSON: no NaN/Infinity token OR string.

    An undefined metric (a fold entirely flat over its test window has no Sharpe)
    is serialized as ``null`` -- the only strict-JSON representation; "NaN" strings
    are non-standard and break jq and most non-Python parsers. The strict parse is
    enforced with a ``parse_constant`` that fails on any bare token. On the
    archived 2022-2024 sample, ETH fold 3 was flat and carried four nulls; on the
    B4 span every fold is measurable, so the current golden must contain NO null
    fold metric -- pinned here so a flat fold reappearing is seen, not skimmed."""

    def _reject(token: str) -> None:
        pytest.fail(f"bare {token} token in metrics.json -- strict JSON forbids it")

    payload = json.loads(METRICS_PATH.read_bytes().decode("utf-8"), parse_constant=_reject)
    assert set(payload) == {"config", "data", "full_sample", "walk_forward"}
    for symbol_block in payload["walk_forward"].values():
        for config_block in symbol_block.values():
            for fold in config_block["folds"]:
                assert fold["test_sharpe"] is not None  # every B4 fold is measurable
                assert fold["test_t_stat"] is not None
    assert '"NaN"' not in METRICS_PATH.read_bytes().decode("utf-8")


def test_golden_metrics_pins_all_data_hashes() -> None:
    """Both timeframes of both symbols must be pinned by SHA-256 in the golden file."""
    payload: dict[str, Any] = json.loads(METRICS_PATH.read_bytes().decode("utf-8"))
    for symbol in ("BTC/USDT", "ETH/USDT"):
        for timeframe in ("1d", "1h"):
            sha = payload["data"][symbol][timeframe]["sha256"]
            assert isinstance(sha, str) and len(sha) == 64


def test_prereg_constants_match_the_dated_readme_prose() -> None:
    """The dated pre-registration prose is frozen; the code constants must match it.

    The bounds are hand-written in the README on purpose (a pre-registration must be
    frozen text, not regenerated output), which leaves them duplicated in the
    ``PREREG_*`` constants that render the generated check. This test pins the two
    together: editing either side alone breaks the build, so the promise "not edited
    since" stays machine-checked.
    """
    readme = README_PATH.read_bytes().decode("utf-8").replace("−", "-")
    assert f"[{PREREG_SHARPE_LO:+.1f}, {PREREG_SHARPE_HI:+.1f}]" in readme
    assert f"|t-stat| < {PREREG_TSTAT_MAX:.0f}" in readme
    assert f"OOS Sharpe > {PREREG_ALARM_SHARPE:.1f}" in readme


def test_config_identity_follows_selection_degeneracy(computed: Computed) -> None:
    """Anchored and rolling produce bit-identical OOS series EXACTLY when they
    select the same parameters on every fold: same picks => same segments =>
    same equity curve. On the archived 2022-2024 sample this held 20/20 and was
    published as a DEGENERACY, not robustness; prediction (b) of the B4
    pre-registration said the span extension must break it -- and it did: BTC's
    rolling run re-selects mid-run (5/50 then 5/100), the first real parameter
    change of the project, and its OOS series diverges from anchored, while ETH
    still picks a single point (10/20) in both configs and stays bit-identical.
    The structural rule is asserted for every symbol, and today's observed state
    is pinned so any silent flip back is seen."""
    identity: dict[str, bool] = {}
    for symbol, by_config in computed.walkforward.items():
        anchored, rolling = by_config["anchored"], by_config["rolling"]
        same_picks = all(
            fold_a.params == fold_r.params
            for fold_a, fold_r in zip(anchored.folds, rolling.folds, strict=True)
        )
        series_equal = bool(anchored.oos.returns.equals(rolling.oos.returns))
        assert same_picks == series_equal  # the structural rule, both directions
        identity[symbol.split("/")[0]] = series_equal
    # observed state after B4 -- prediction (b) realized on BTC, ETH still degenerate
    assert identity == {"BTC": False, "ETH": True}


def test_coverage_convention_numbers_match_the_computed_run(computed: Computed) -> None:
    """The locked 2026-07-27 coverage-convention prose quotes data-derived numbers
    (all-bars vs exposed-only Sharpe and t-stat, exposed bar counts, magnitude
    ratio); every one is recomputed here from the shared run -- exposed-only
    Sharpe = mean/std(ddof=1) over the non-flat bars, annualized sqrt(365);
    exposed t-stat = the repo's bar-count convention applied to the exposed bar
    count -- and must appear in the README verbatim."""
    readme = README_PATH.read_bytes().decode("utf-8").replace("−", "-")
    values: dict[str, tuple[float, float, float, float, int]] = {}
    for symbol, by_config in computed.walkforward.items():
        result = by_config["anchored"]
        r = result.oos.returns.to_numpy(dtype="float64")
        p = result.oos.positions.to_numpy(dtype="float64")
        exposed = r[p != 0.0]
        sr_exp = float(exposed.mean() / exposed.std(ddof=1)) * math.sqrt(365.0)
        t_exp = sr_exp * math.sqrt(len(exposed) / calendar_bars_per_year(RESULTS_TIMEFRAME))
        assert len(exposed) == result.n_bars_exposed  # engine count == direct count
        values[symbol.split("/")[0]] = (
            result.metrics["sharpe"],
            sr_exp,
            result.metrics["t_stat"],
            t_exp,
            result.n_bars_exposed,
        )
    (oos_bars,) = {
        len(result.oos.returns)
        for by_config in computed.walkforward.values()
        for result in by_config.values()
    }
    eth, btc = values["ETH"], values["BTC"]
    assert f"Sharpe {eth[0]:.4f} on all {oos_bars} bars" in readme
    assert f"**{eth[1]:.4f}** on" in readme
    assert f"its {eth[4]} exposed bars" in readme
    magnitude = (abs(eth[1] / eth[0]) - 1.0) * 100.0
    assert f"({magnitude:.0f}% larger in magnitude)" in readme
    assert f"({eth[2]:.3f} → {eth[3]:.3f})" in readme
    assert f"BTC: {btc[0]:.4f} → {btc[1]:.4f}, t {btc[2]:.3f} → {btc[3]:.3f}" in readme


def test_carried_boundaries_are_pinned_per_symbol_and_config(computed: Computed) -> None:
    """A3 pin, re-pinned at B4 (the previous pin -- exactly 1 everywhere, at
    2024-11-17 -> 2024-11-18 -- fell as designed when the sample moved): BTC
    anchored carries at folds 1->2, 2->3 and 3->4 (2025-01-27/28, 2025-06-06/07,
    2025-10-13/14); BTC rolling carries only at 2->3 -- its fold 1->2 boundary is
    the project's first real parameter change (5/50 -> 5/100) and resets flat;
    ETH carries at 2->3 and 3->4 in both configs. This count moves the published
    numbers with it, so it stays asserted from the engine's own counter."""
    expected = {
        ("BTC/USDT", "anchored"): 3,
        ("BTC/USDT", "rolling"): 1,
        ("ETH/USDT", "anchored"): 2,
        ("ETH/USDT", "rolling"): 2,
    }
    for symbol, by_config in computed.walkforward.items():
        for config_name, result in by_config.items():
            assert result.n_carried_boundaries == expected[(symbol, config_name)], (
                f"{symbol} {config_name}: expected "
                f"{expected[(symbol, config_name)]} carried boundaries, "
                f"got {result.n_carried_boundaries}"
            )


def test_2022_2024_slice_reproduces_the_archived_golden_bit_for_bit(
    slice_2022_2024: dict[str, dict[str, WalkForwardResult]],
) -> None:
    """Prediction (d) of the B4 pre-registration, held as a PERMANENT guard: the
    archived 2022-2024 OOS numbers (results/archive/metrics-2022-2024.json,
    frozen at step 0) must be reproducible from the CURRENT data's
    2022-01-01..2024-12-31 slice, bit for bit -- the old sample is an exact
    subset of the new one. A failure here means either Binance restated its
    history or a result depends on the extent of the frame around it; both are
    defects that outrank any span extension."""
    archive = json.loads(ARCHIVE_PATH.read_bytes().decode("utf-8"))
    for symbol, by_config in slice_2022_2024.items():
        for config_name, result in by_config.items():
            archived_oos = archive["walk_forward"][symbol][config_name]["oos"]
            for key in (
                "sharpe",
                "sharpe_se",
                "t_stat",
                "total_return",
                "max_drawdown",
                "annualized_turnover",
                "sortino",
                "win_rate",
                "flat_share",
            ):
                assert repr(result.metrics[key]) == repr(archived_oos[key]), (
                    f"{symbol} {config_name} {key}: slice={result.metrics[key]!r} "
                    f"archive={archived_oos[key]!r} -- Binance restatement or "
                    "frame-extent dependence; this outranks B4"
                )


def test_prereg_correction_note_numbers_match_the_2022_2024_slice(
    computed: Computed,
    slice_2022_2024: dict[str, dict[str, WalkForwardResult]],
) -> None:
    """Step 4-bis of B4-B, the method decision written down: the dated 26/07
    correction note keeps its numbers VERBATIM ("the original text above is kept
    verbatim" is its own first line), and those numbers stay machine-checked --
    not against the CURRENT run (which now covers 2017-2026 and would force a
    history rewrite), but against the 2022-01-01..2024-12-31 SLICE of the
    current data, which prediction (d) guarantees reproduces the old sample
    exactly. History stays history; the numbers stay recomputable; and a failure
    here is a Binance restatement or a frame-extent dependence, not prose rot."""
    readme = README_PATH.read_bytes().decode("utf-8").replace("−", "-")

    (oos_bars,) = {
        len(result.oos.returns)
        for by_config in slice_2022_2024.values()
        for result in by_config.values()
    }
    years = oos_bars / calendar_bars_per_year(RESULTS_TIMEFRAME)
    theoretical_se = 1.0 / math.sqrt(years)  # the note's "1/sqrt(0.600 years) = 1.29"
    assert f"1/√{years:.3f} years = {theoretical_se:.2f}" in readme
    width = (PREREG_SHARPE_HI - PREREG_SHARPE_LO) / theoretical_se
    assert f"**{width:.2f} SE** wide" in readme

    deviations: dict[str, tuple[float, float]] = {}
    for symbol, by_config in slice_2022_2024.items():
        result = by_config["anchored"]
        m = result.metrics
        prices_slice = computed.prices[symbol].loc["2022-01-01":"2024-12-31"]
        splice = _splice_stats(prices_slice, result)
        spliced_dev = (PREREG_SHARPE_LO - m["sharpe"]) / m["sharpe_se"]
        standalone_dev = (PREREG_SHARPE_LO - splice["standalone_sharpe"]) / splice[
            "standalone_sharpe_se"
        ]
        deviations[symbol.split("/")[0]] = (spliced_dev, standalone_dev)
    btc, eth = deviations["BTC"], deviations["ETH"]
    assert f"**{btc[0]:.2f} SE (BTC)** and **{eth[0]:.2f} SE (ETH)**" in readme
    assert f"({btc[1]:.2f} SE and {eth[1]:.2f} SE under the flat-restart" in readme
